---
api_version: v1
data:
    codes: codes.yaml
    categories: categories.yaml
schemas:
    codes: schemas/codes.schema.json
    categories: schemas/categories.schema.json
    codes_meta: schemas/codes_meta.schema.json
    metadata: schemas/metadata.schema.json
build:
    html: src/build/html
    static_src: src/static
    schema_prefix: schemas/v1
